using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using CliWrap;
using CliWrap.Buffered;
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Containers;
using DotNet.Testcontainers.Networks;
using Microsoft.Playwright;
using NUnit.Framework;
using Testcontainers.Playwright;
using Testcontainers.PostgreSql;
using Tests.TestSupport;
using WireMock.Net.Testcontainers;

namespace Tests.SystemTests;

[SetUpFixture]
public class SystemTestsFixture
{
    private const string AuthUsername = "systemtestuser";
    private const string AuthPassword = "systemtestpass";
    private const string PostgresNetworkAlias = "postgres";
    private const string PostgresDatabase = "podbridge";
    private const string PostgresUsername = "podbridge";
    private const string PostgresPassword = "podbridge-system-test-pw";

    // Pre-computed PBKDF2 hashes (via PodBridge.Logic.Security.CredentialHasher.Hash) of the plaintext
    // constants above, hardcoded here rather than computed at test time so this system test stays a true
    // black box against the running container - no internal API of the app under test is referenced - and
    // doubles as an end-to-end check that a hash generated by CredentialHasher/New-CredentialHash.ps1 is
    // actually accepted by the running app.
    private const string AuthUsernameHash = "210000.nZjI6mJkj3Ujwf1K/rPW2Q==.Otz5nPj542gzZCM95nRHJqAO6nuii+dASOlDFsUhY4k=";
    private const string AuthPasswordHash = "210000.znMK/DiN+RUOguYjDYTI5g==.rQNjez3qRmZ/hX+gcYm9u/LZ8KK8K2Q0tXX0Z2FI0yE=";

    private CancellationTokenSource _cancellationTokenSource = null!;
    private INetwork? _network;
    private WireMockContainer? _wireMockContainer;
    private PostgreSqlContainer? _postgresContainer;
    private IContainer? _podBridgeContainer;
    private PlaywrightContainer? _playwrightContainer;
    private IPlaywright? _playwright;
    private IBrowser? _browser;

    public static Uri PodBridgeBaseAddress { get; private set; } = null!;
    public static Uri PodBridgeInternalAddress { get; private set; } = null!;
    public static string PostgresConnectionString { get; private set; } = null!;
    public static IBrowser Browser { get; private set; } = null!;

    [OneTimeSetUp]
    public async Task OneTimeSetUp()
    {
        // 10 minutes to cover: Docker image publish/build, container startups, and pulling the ~1-2GB
        // Playwright image on a cold cache.
        _cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromMinutes(10));

        try
        {
            var imageTag = $"0.0.0-system-test-{DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture)}";

            // The Docker image build has no dependency on the network/other containers, and WireMock/
            // Postgres/Playwright have no dependency on each other or on the image build - run all four
            // concurrently. Only the PodBridge container itself needs both the finished image and the
            // network to exist, so it is started last, once everything above has completed.
            var imageBuildTask = BuildDockerImageAsync(imageTag);

            _network = new NetworkBuilder().Build();
            await _network.CreateAsync(_cancellationTokenSource.Token);

            var wireMockTask = StartWireMockContainerAsync();
            var postgresTask = StartPostgresContainerAsync();
            var playwrightContainerTask = StartPlaywrightContainerAsync();

            await Task.WhenAll(imageBuildTask, wireMockTask, postgresTask, playwrightContainerTask);

            _wireMockContainer = await wireMockTask;
            _postgresContainer = await postgresTask;
            _playwrightContainer = await playwrightContainerTask;
            _podBridgeContainer = await StartPodBridgeContainerAsync(imageTag);

            PodBridgeBaseAddress = GetPodBridgeBaseAddress(_podBridgeContainer);
            PodBridgeInternalAddress = new Uri("http://podbridge:8080/");
            PostgresConnectionString = _postgresContainer.GetConnectionString();

            _playwright = await Playwright.CreateAsync();
            _browser = await _playwright.Chromium.ConnectAsync(_playwrightContainer!.GetConnectionString());
            Browser = _browser;
        }
        catch
        {
            await Cleanup();
            throw;
        }
    }

    [OneTimeTearDown]
    public async Task OneTimeTearDown()
    {
        await Cleanup();
    }

    private static async Task CleanupPodBridgeContainerAsync(IContainer container, CancellationToken cancellationToken)
    {
        await container.StopAsync(cancellationToken);

        if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("GITHUB_ACTIONS")))
        {
            var imageName = container.Image.FullName;

            try
            {
                await Cli.Wrap("docker")
                    .WithArguments(new[] { "rmi", "--force", imageName })
                    .ExecuteAsync(cancellationToken);
            }
            catch
            {
                // Best effort cleanup
            }
        }
    }

    private static Uri GetPodBridgeBaseAddress(IContainer container)
    {
        var port = container.GetMappedPublicPort(8080);
        return new Uri($"http://localhost:{port}");
    }

    // CliWrap's CommandTask<T> implements IDisposable and is correctly disposed via the using declaration
    // below; the analyzer's dataflow incorrectly extends that "needs disposal" flag to the plain
    // BufferedCommandResult value produced by awaiting it, which itself does not implement IDisposable.
    [SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created", Justification = "False positive: the actual disposable (CommandTask<T>) is disposed via 'using'; 'result' is a plain non-disposable BufferedCommandResult.")]
    private static async Task BuildDockerImageAsync(string imageTag)
    {
        // PodBridge intentionally has no Dockerfile (see README.md) - the image is built via the .NET SDK's
        // built-in container publishing support (Microsoft.NET.Build.Containers, chiseled base image), routed
        // through mu88.Shared's PublishContainersForMultipleFamilies target (same as the production release
        // build). DoNotApplyGitHubScope=true keeps the image local (no ghcr.io push) so Testcontainers can
        // reference it by its plain repository:tag name; without it, mu88.Shared.targets would auto-redirect
        // the build to push to ghcr.io whenever GITHUB_ACTIONS is set, leaving no local image to start.
        // --os linux --arch amd64 restricts the build to a single-platform image (matching the sibling
        // PodScrub repo): without it, the target produces a multi-arch image index (linux-x64 + linux-arm64),
        // which Docker can only load locally when its containerd image store is enabled - not the case on
        // GitHub-hosted runners, causing "CONTAINER1020: containerd image store is not enabled" at load time.
        var repoRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
        using var commandTask = Cli.Wrap("dotnet")
            .WithArguments(new[]
            {
                "publish", "src/PodBridge.Api/PodBridge.Api.csproj",
                "--os", "linux",
                "--arch", "amd64",
                "-t:PublishContainersForMultipleFamilies",
                $"-p:ReleaseVersion={imageTag}",
                "-p:IsRelease=false",
                "-p:DoNotApplyGitHubScope=true",
                "-p:ContainerRepository=podbridge-api",
            })
            .WithWorkingDirectory(repoRoot)
            .WithValidation(CommandResultValidation.None)
            .ExecuteBufferedAsync();
        var result = await commandTask;

        if (result.ExitCode != 0)
        {
            throw new InvalidOperationException($"Container publish failed with exit code {result.ExitCode.ToString(CultureInfo.InvariantCulture)}. Output: {result.StandardOutput}. Error: {result.StandardError}");
        }
    }

    private async Task Cleanup()
    {
        await _cancellationTokenSource.CancelAsync();

        // Cleanup must use its own token: the token above is deliberately cancelled to stop any
        // in-flight test operations, but Testcontainers cleanup calls need a fresh, non-cancelled token.
        using var cleanupCancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(30));

        if (_browser != null)
        {
            await _browser.CloseAsync();
        }

        if (_playwright != null)
        {
            _playwright.Dispose();
        }

        if (_playwrightContainer != null)
        {
            await _playwrightContainer.DisposeAsync();
        }

        if (_podBridgeContainer != null)
        {
            await CleanupPodBridgeContainerAsync(_podBridgeContainer, cleanupCancellationTokenSource.Token);
        }

        if (_wireMockContainer != null)
        {
            await _wireMockContainer.DisposeAsync();
        }

        if (_postgresContainer != null)
        {
            await _postgresContainer.DisposeAsync();
        }

        if (_network != null)
        {
            await _network.DisposeAsync();
        }

        _cancellationTokenSource.Dispose();
    }

    private async Task<WireMockContainer> StartWireMockContainerAsync()
    {
        var mappingsDir = Path.Combine(AppContext.BaseDirectory, "testData", "system", "wiremock-mappings");
        var container = new WireMockContainerBuilder()
            .WithImage(TestcontainerImages.GetImageReference("wiremock"))
            .WithNetwork(_network)
            .WithNetworkAliases("wiremock")
            .WithMappings(mappingsDir)
            .Build();

        await container.StartAsync(_cancellationTokenSource.Token);
        return container;
    }

    private async Task<PostgreSqlContainer> StartPostgresContainerAsync()
    {
        var container = new PostgreSqlBuilder(TestcontainerImages.GetImageReference("postgres"))
            .WithNetwork(_network)
            .WithNetworkAliases(PostgresNetworkAlias)
            .WithDatabase(PostgresDatabase)
            .WithUsername(PostgresUsername)
            .WithPassword(PostgresPassword)
            .Build();

        await container.StartAsync(_cancellationTokenSource.Token);
        return container;
    }

    private async Task<IContainer> StartPodBridgeContainerAsync(string imageTag)
    {
        var imageName = $"podbridge-api:{imageTag}-chiseled";

        // Exercises the real PostgresConnectionStringResolver indirection path (not the ConnectionStrings
        // fallback): the hosting platform supplies raw PGHOST/PGPORT/etc. env vars, and PodBridge__Database__*
        // tells the app which env var names to read.
        var builder = new ContainerBuilder(imageName)
            .WithNetwork(_network)
            .WithNetworkAliases("podbridge")
            .WithPortBinding(8080, assignRandomHostPort: true)
            .WithWaitStrategy(Wait.ForUnixContainer().UntilHttpRequestIsSucceeded(r => r.ForPort(8080).ForPath("/healthz")))
            .WithEnvironment("ASPNETCORE_ENVIRONMENT", "Production")
            .WithEnvironment("PodBridge__RefreshInterval", "00:00:10")
            .WithEnvironment("PodBridge__RateLimitingPermitLimit", "100")
            .WithEnvironment("PodBridge__RateLimitingWindowMinutes", "5")
            .WithEnvironment("PodBridge__GraphQlEndpoint", "http://wiremock/graphql")
            .WithEnvironment("PodBridge__Database__HostEnvVar", "PGHOST")
            .WithEnvironment("PodBridge__Database__PortEnvVar", "PGPORT")
            .WithEnvironment("PodBridge__Database__UsernameEnvVar", "PGUSER")
            .WithEnvironment("PodBridge__Database__PasswordEnvVar", "PGPASSWORD")
            .WithEnvironment("PodBridge__Database__DatabaseNameEnvVar", "PGDATABASE")
            .WithEnvironment("PGHOST", PostgresNetworkAlias)
            .WithEnvironment("PGPORT", "5432")
            .WithEnvironment("PGUSER", PostgresUsername)
            .WithEnvironment("PGPASSWORD", PostgresPassword)
            .WithEnvironment("PGDATABASE", PostgresDatabase)
            .WithEnvironment("PodBridge__Auth__Enabled", "true")
            .WithEnvironment("PodBridge__Auth__UsernameHash", AuthUsernameHash)
            .WithEnvironment("PodBridge__Auth__PasswordHash", AuthPasswordHash);

        var container = builder.Build();
        await container.StartAsync(_cancellationTokenSource.Token);
        return container;
    }

    private async Task<PlaywrightContainer> StartPlaywrightContainerAsync()
    {
        var container = new PlaywrightBuilder(TestcontainerImages.GetImageReference("playwright"))
            .WithNetwork(_network)
            .Build();

        await container.StartAsync(_cancellationTokenSource.Token);
        return container;
    }
}
