using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Net;
using System.Text;
using System.Xml.Linq;
using CliWrap;
using CliWrap.Buffered;
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Containers;
using DotNet.Testcontainers.Networks;
using FluentAssertions;
using FluentAssertions.Web;
using NUnit.Framework;
using WireMock.Net.Testcontainers;

namespace Tests.SystemTests;

[Category("System")]
public class PodBridgeSystemTests
{
    private const string FixtureShowId = "fixture-show";
    private const string FixtureShowDisplayName = "System Test Fixture Show";
    private const string SystemTestAuthUsername = "systemtestuser";
    private const string SystemTestAuthPassword = "systemtestpass";

    // Pre-computed PBKDF2 hashes (via PodBridge.Logic.Security.CredentialHasher.Hash) of the plaintext
    // constants above, hardcoded here rather than computed at test time so this system test stays a true
    // black box against the running container - no internal API of the app under test is referenced - and
    // doubles as an end-to-end check that a hash generated by CredentialHasher/New-CredentialHash.ps1 is
    // actually accepted by the running app.
    private const string SystemTestAuthUsernameHash = "210000.nZjI6mJkj3Ujwf1K/rPW2Q==.Otz5nPj542gzZCM95nRHJqAO6nuii+dASOlDFsUhY4k=";
    private const string SystemTestAuthPasswordHash = "210000.znMK/DiN+RUOguYjDYTI5g==.rQNjez3qRmZ/hX+gcYm9u/LZ8KK8K2Q0tXX0Z2FI0yE=";

    private CancellationTokenSource _cancellationTokenSource = null!;
    private INetwork? _network;
    private WireMockContainer? _wireMockContainer;
    private IContainer? _podBridgeContainer;

    [SetUp]
    public void Setup()
    {
        _cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromMinutes(3));
    }

    [TearDown]
    public async Task TearDown()
    {
        await _cancellationTokenSource.CancelAsync();

        // Cleanup must use its own token: the token above is deliberately cancelled to stop any
        // in-flight test operations, but Testcontainers cleanup calls need a fresh, non-cancelled token.
        using var cleanupCancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(30));

        if (_podBridgeContainer != null)
        {
            await CleanupPodBridgeContainerAsync(_podBridgeContainer, cleanupCancellationTokenSource.Token);
        }

        if (_wireMockContainer != null)
        {
            await _wireMockContainer.DisposeAsync();
        }

        if (_network != null)
        {
            await _network.DisposeAsync();
        }

        _cancellationTokenSource.Dispose();
    }

    [Test]
    [SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP014:Use a single instance of HttpClient", Justification = "Short-lived system test client targeting a Testcontainers-assigned port that only exists for the duration of this test; a shared instance isn't feasible.")]
    public async Task AppRunningInDocker_ShouldSyncPodcastFromWireMockAndExposeRssFeed()
    {
        // Arrange
        // Must be a valid SemVer string (not just an arbitrary tag suffix): since mu88.Shared.targets now also
        // sets the compiled assembly's Version from ReleaseVersion (in addition to the container tag), an
        // invalid version string like the previous "system-test-<timestamp>" fails GenerateAssemblyInfo with
        // NETSDK1018.
        var imageTag = $"0.0.0-system-test-{DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture)}";
        await BuildDockerImageAsync(imageTag);

        _network = new NetworkBuilder().Build();
        await _network.CreateAsync(_cancellationTokenSource.Token);

        _wireMockContainer = await StartWireMockContainerAsync();
        _podBridgeContainer = await StartPodBridgeContainerAsync(imageTag, authEnabled: false);

        using var httpClient = new HttpClient { BaseAddress = GetPodBridgeBaseAddress() };

        // Act - Wait for background worker to populate cache
        using var podcastsResponse = await WaitForFeedToBePopulatedAsync(httpClient);
        using var feedResponse = await httpClient.GetAsync($"/api/podcasts/{FixtureShowId}", _cancellationTokenSource.Token);

        // Assert
        podcastsResponse.Should().Be200Ok();
        var podcastsJson = await podcastsResponse.Content.ReadAsStringAsync(_cancellationTokenSource.Token);
        podcastsJson.Should().Contain(FixtureShowId).And.Contain(FixtureShowDisplayName);

        feedResponse.Should().Be200Ok();
        feedResponse.Content.Headers.ContentType?.MediaType.Should().Be("application/rss+xml");

        var feedXml = await feedResponse.Content.ReadAsStringAsync(_cancellationTokenSource.Token);
        var doc = XDocument.Parse(feedXml);
        var channel = doc.Root!.Element("channel")!;
        channel.Element("title")!.Value.Should().Be(FixtureShowDisplayName);

        var items = channel.Elements("item").ToList();
        items.Should().HaveCount(2);

        // The RSS feed lists episodes newest-first (RssFeed.cs orders by PublishDate descending),
        // so "Episode 2" (published later) appears before "Episode 1".
        items[0].Element("title")!.Value.Should().Be("Episode 2: The Journey");
        items[1].Element("title")!.Value.Should().Be("Episode 1: The Beginning");
    }

    [Test]
    [SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP014:Use a single instance of HttpClient", Justification = "Short-lived system test clients targeting a Testcontainers-assigned port that only exists for the duration of this test; a shared instance isn't feasible.")]
    public async Task AppRunningInDocker_WithBasicAuthEnabled_ShouldEnforceAuthentication()
    {
        // Arrange
        // See the comment in the previous test for why this must be a valid SemVer string.
        var imageTag = $"0.0.0-system-test-auth-{DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture)}";
        await BuildDockerImageAsync(imageTag);

        _network = new NetworkBuilder().Build();
        await _network.CreateAsync(_cancellationTokenSource.Token);

        _wireMockContainer = await StartWireMockContainerAsync();
        _podBridgeContainer = await StartPodBridgeContainerAsync(imageTag, authEnabled: true);

        using var httpClientWithoutAuth = new HttpClient { BaseAddress = GetPodBridgeBaseAddress() };
        using var httpClientWithAuth = new HttpClient { BaseAddress = GetPodBridgeBaseAddress() };

        var credentials = Convert.ToBase64String(Encoding.ASCII.GetBytes($"{SystemTestAuthUsername}:{SystemTestAuthPassword}"));
        httpClientWithAuth.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", credentials);

        // Act & Assert - /healthz should be accessible without auth
        using var healthCheck = await httpClientWithoutAuth.GetAsync("healthz", _cancellationTokenSource.Token);
        healthCheck.Should().Be200Ok();

        // /podcasts without auth should return 401
        using var podcastsWithoutAuth = await httpClientWithoutAuth.GetAsync("/api/podcasts", _cancellationTokenSource.Token);
        podcastsWithoutAuth.StatusCode.Should().Be(HttpStatusCode.Unauthorized);

        // /podcasts with auth should work
        using var podcastsResponse = await WaitForFeedToBePopulatedAsync(httpClientWithAuth);
        podcastsResponse.Should().Be200Ok();

        // /feeds without auth should return 401
        using var feedWithoutAuth = await httpClientWithoutAuth.GetAsync($"/api/podcasts/{FixtureShowId}", _cancellationTokenSource.Token);
        feedWithoutAuth.StatusCode.Should().Be(HttpStatusCode.Unauthorized);

        // /feeds with auth should work
        using var feedWithAuth = await httpClientWithAuth.GetAsync($"/api/podcasts/{FixtureShowId}", _cancellationTokenSource.Token);
        feedWithAuth.Should().Be200Ok();
    }

    private static async Task CleanupPodBridgeContainerAsync(IContainer container, CancellationToken cancellationToken)
    {
        await container.StopAsync(cancellationToken);

        if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("GITHUB_ACTIONS")))
        {
            var imageName = container.Image.FullName;

            try
            {
                await Cli.Wrap("docker")
                    .WithArguments(new[] { "rmi", "--force", imageName })
                    .ExecuteAsync(cancellationToken);
            }
            catch
            {
                // Best effort cleanup
            }
        }
    }

    private async Task<WireMockContainer> StartWireMockContainerAsync()
    {
        var mappingsDir = Path.Combine(AppContext.BaseDirectory, "testData", "system", "wiremock-mappings");
        var container = new WireMockContainerBuilder()
            .WithNetwork(_network)
            .WithNetworkAliases("wiremock")
            .WithMappings(mappingsDir)
            .Build();

        await container.StartAsync(_cancellationTokenSource.Token);
        return container;
    }

    private async Task<IContainer> StartPodBridgeContainerAsync(string imageTag, bool authEnabled)
    {
        var imageName = $"podbridge-api:{imageTag}-chiseled";
        var builder = new ContainerBuilder(imageName)
            .WithNetwork(_network)
            .WithNetworkAliases("podbridge")
            .WithPortBinding(8080, assignRandomHostPort: true)
            .WithWaitStrategy(Wait.ForUnixContainer().UntilHttpRequestIsSucceeded(r => r.ForPort(8080).ForPath("/healthz")))
            .WithEnvironment("ASPNETCORE_ENVIRONMENT", "Production")
            .WithEnvironment("PodBridge__RefreshIntervalMinutes", "1")
            .WithEnvironment("PodBridge__RateLimitingPermitLimit", "100")
            .WithEnvironment("PodBridge__RateLimitingWindowMinutes", "5")
            .WithEnvironment("PodBridge__GraphQlEndpoint", "http://wiremock/graphql")
            .WithEnvironment("PodBridge__Podcasts__0__PodcastId", FixtureShowId)
            .WithEnvironment("PodBridge__Podcasts__0__ShowId", "fixture-show-id");

        if (authEnabled)
        {
            builder = builder
                .WithEnvironment("PodBridge__Auth__Enabled", "true")
                .WithEnvironment("PodBridge__Auth__UsernameHash", SystemTestAuthUsernameHash)
                .WithEnvironment("PodBridge__Auth__PasswordHash", SystemTestAuthPasswordHash);
        }

        var container = builder.Build();
        await container.StartAsync(_cancellationTokenSource.Token);
        return container;
    }

    // CliWrap's CommandTask<T> implements IDisposable and is correctly disposed via the using declaration
    // below; the analyzer's dataflow incorrectly extends that "needs disposal" flag to the plain
    // BufferedCommandResult value produced by awaiting it, which itself does not implement IDisposable.
    [SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP001:Dispose created", Justification = "False positive: the actual disposable (CommandTask<T>) is disposed via 'using'; 'result' is a plain non-disposable BufferedCommandResult.")]
    private async Task BuildDockerImageAsync(string imageTag)
    {
        // PodBridge intentionally has no Dockerfile (see README.md) - the image is built via the .NET SDK's
        // built-in container publishing support (Microsoft.NET.Build.Containers, chiseled base image), routed
        // through mu88.Shared's PublishContainersForMultipleFamilies target (same as the production release
        // build). DoNotApplyGitHubScope=true keeps the image local (no ghcr.io push) so Testcontainers can
        // reference it by its plain repository:tag name; without it, mu88.Shared.targets would auto-redirect
        // the build to push to ghcr.io whenever GITHUB_ACTIONS is set, leaving no local image to start.
        // --os linux --arch amd64 restricts the build to a single-platform image (matching the sibling
        // PodScrub repo): without it, the target produces a multi-arch image index (linux-x64 + linux-arm64),
        // which Docker can only load locally when its containerd image store is enabled - not the case on
        // GitHub-hosted runners, causing "CONTAINER1020: containerd image store is not enabled" at load time.
        var repoRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
        using var commandTask = Cli.Wrap("dotnet")
            .WithArguments(new[]
            {
                "publish", "src/PodBridge.Api/PodBridge.Api.csproj",
                "--os", "linux",
                "--arch", "amd64",
                "-t:PublishContainersForMultipleFamilies",
                $"-p:ReleaseVersion={imageTag}",
                "-p:IsRelease=false",
                "-p:DoNotApplyGitHubScope=true",
                "-p:ContainerRepository=podbridge-api",
            })
            .WithWorkingDirectory(repoRoot)
            .WithValidation(CommandResultValidation.None)
            .ExecuteBufferedAsync(_cancellationTokenSource.Token);
        var result = await commandTask;

        if (result.ExitCode != 0)
        {
            throw new InvalidOperationException($"Container publish failed with exit code {result.ExitCode.ToString(CultureInfo.InvariantCulture)}. Output: {result.StandardOutput}. Error: {result.StandardError}");
        }
    }

    private Uri GetPodBridgeBaseAddress()
    {
        if (_podBridgeContainer == null)
        {
            throw new InvalidOperationException("PodBridge container not started");
        }

        var port = _podBridgeContainer.GetMappedPublicPort(8080);
        return new Uri($"http://localhost:{port}");
    }

    // The analyzer cannot follow the "return the live response, dispose it otherwise" control flow of this
    // polling loop: on the success path ownership of the still-open response is transferred to the caller,
    // on every other path it is disposed before the next attempt. Both are intentional, not a leak.
    [SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP011:Don't return disposed instance", Justification = "Response is only disposed on the non-returning loop paths; the returned instance is always live.")]
    [SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP017:Prefer using", Justification = "A using declaration would dispose the response before it can be returned to the caller on the success path.")]
    private async Task<HttpResponseMessage> WaitForFeedToBePopulatedAsync(HttpClient httpClient)
    {
        const int maxAttempts = 30;
        var delayBetweenAttempts = TimeSpan.FromSeconds(2);

        for (var attempt = 0; attempt < maxAttempts; attempt++)
        {
            var response = await httpClient.GetAsync("/api/podcasts", _cancellationTokenSource.Token);
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync(_cancellationTokenSource.Token);
                if (content.Contains(FixtureShowDisplayName, StringComparison.Ordinal))
                {
                    return response; // Caller owns disposal
                }
            }

            response.Dispose();

            if (attempt < maxAttempts - 1)
            {
                await Task.Delay(delayBetweenAttempts, _cancellationTokenSource.Token);
            }
        }

        var totalWaitSeconds = maxAttempts * delayBetweenAttempts.TotalSeconds;
        throw new TimeoutException($"Feed not populated after {maxAttempts.ToString(CultureInfo.InvariantCulture)} attempts over {totalWaitSeconds.ToString(CultureInfo.InvariantCulture)} seconds");
    }
}
